export const HAKI_ABI = [
  {
    type: "constructor",
    inputs: [
      { name: "_wrapper", type: "address", internalType: "address" },
      { name: "_resolver", type: "address", internalType: "address" },
      { name: "_parentNode", type: "bytes32", internalType: "bytes32" },
      { name: "_marketResolver", type: "address", internalType: "address" },
      { name: "_arbitrator", type: "address", internalType: "address" },
      { name: "_token", type: "address", internalType: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "arbitrator",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "challengeDeposit",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "challengeMarketResult",
    inputs: [{ name: "node", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "challengePeriod",
    inputs: [],
    outputs: [{ name: "", type: "uint64", internalType: "uint64" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "claimWinnings",
    inputs: [
      { name: "node", type: "bytes32", internalType: "bytes32" },
      { name: "proof", type: "bytes32[]", internalType: "bytes32[]" },
      { name: "shares", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "createMarket",
    inputs: [
      { name: "label", type: "string", internalType: "string" },
      { name: "description", type: "string", internalType: "string" },
      { name: "options", type: "string", internalType: "string" },
      { name: "expiry", type: "uint64", internalType: "uint64" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "finalizeAndRelease",
    inputs: [{ name: "node", type: "bytes32", internalType: "bytes32" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "hasWithdrawn",
    inputs: [
      { name: "", type: "bytes32", internalType: "bytes32" },
      { name: "", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "marketResolver",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "markets",
    inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      { name: "creator", type: "address", internalType: "address" },
      { name: "resultTimestamp", type: "uint256", internalType: "uint256" },
      { name: "stateRoot", type: "bytes32", internalType: "bytes32" },
      { name: "resolved", type: "bool", internalType: "bool" },
      { name: "challenged", type: "bool", internalType: "bool" },
      { name: "label", type: "string", internalType: "string" },
      { name: "expiry", type: "uint64", internalType: "uint64" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nameWrapper",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract INameWrapper" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "onERC1155BatchReceived",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256[]", internalType: "uint256[]" },
      { name: "", type: "uint256[]", internalType: "uint256[]" },
      { name: "", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "onERC1155Received",
    inputs: [
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "address", internalType: "address" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "uint256", internalType: "uint256" },
      { name: "", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "", type: "bytes4", internalType: "bytes4" }],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "parentNode",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "publicResolver",
    inputs: [],
    outputs: [
      { name: "", type: "address", internalType: "contract PublicResolver" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "resolveByArbitrator",
    inputs: [
      { name: "node", type: "bytes32", internalType: "bytes32" },
      { name: "option", type: "string", internalType: "string" },
      { name: "stateRoot", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "submitMarketResult",
    inputs: [
      { name: "node", type: "bytes32", internalType: "bytes32" },
      { name: "option", type: "string", internalType: "string" },
      { name: "stateRoot", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "supportsInterface",
    inputs: [{ name: "interfaceId", type: "bytes4", internalType: "bytes4" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "token",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "MarketChallenged",
    inputs: [
      { name: "node", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "challenger",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MarketCreated",
    inputs: [
      { name: "node", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "creator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "label", type: "string", indexed: false, internalType: "string" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "MarketResolved",
    inputs: [
      { name: "node", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "winner",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "wasChallenged",
        type: "bool",
        indexed: false,
        internalType: "bool",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ResultSubmitted",
    inputs: [
      { name: "node", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "option",
        type: "string",
        indexed: false,
        internalType: "string",
      },
      {
        name: "stateRoot",
        type: "bytes32",
        indexed: false,
        internalType: "bytes32",
      },
    ],
    anonymous: false,
  },
] as const;